// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Spovest.Persistence.Contexts;

#nullable disable

namespace Spovest.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250610155913_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Spovest.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsWithdrawBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Spovest.Domain.Entities.BalanceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalBalance")
                        .HasColumnType("numeric");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BalanceHistory");
                });

            modelBuilder.Entity("Spovest.Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtAdd")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("PlayerId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Spovest.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Assists")
                        .HasColumnType("numeric");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Ftps")
                        .HasColumnType("numeric");

                    b.Property<int>("Games")
                        .HasColumnType("integer");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Minutes")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Points")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rebounds")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Steals")
                        .HasColumnType("numeric");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assists = 7.8m,
                            Ftps = 0.73m,
                            Games = 72,
                            Img = "/images/player_search/avatar_3.png",
                            Minutes = 36.2m,
                            Name = "Lebron James",
                            Points = 28.5m,
                            Rebounds = 8.3m,
                            Steals = 1.6m,
                            TeamId = 1,
                            TeamName = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 2,
                            Assists = 3.1m,
                            Ftps = 0.78m,
                            Games = 65,
                            Img = "/images/player_search/avatar_5.png",
                            Minutes = 32.5m,
                            Name = "Anthony Davis",
                            Points = 22.4m,
                            Rebounds = 10.2m,
                            Steals = 1.8m,
                            TeamId = 1,
                            TeamName = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 3,
                            Assists = 8.4m,
                            Ftps = 0.67m,
                            Games = 70,
                            Img = "/images/player_search/avatar_1.png",
                            Minutes = 34.0m,
                            Name = "Russell Westbrook",
                            Points = 18.2m,
                            Rebounds = 7.5m,
                            Steals = 1.3m,
                            TeamId = 1,
                            TeamName = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 4,
                            Assists = 6.2m,
                            Ftps = 0.82m,
                            Games = 68,
                            Img = "/images/player_search/avatar_6.png",
                            Minutes = 29.8m,
                            Name = "D'Angelo Russell",
                            Points = 15.3m,
                            Rebounds = 3.4m,
                            Steals = 1.1m,
                            TeamId = 1,
                            TeamName = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 5,
                            Assists = 2.9m,
                            Ftps = 0.85m,
                            Games = 60,
                            Img = "/images/player_search/avatar_2.png",
                            Minutes = 21.4m,
                            Name = "Austin Reaves",
                            Points = 9.7m,
                            Rebounds = 2.8m,
                            Steals = 0.9m,
                            TeamId = 1,
                            TeamName = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 6,
                            Assists = 6.5m,
                            Ftps = 0.91m,
                            Games = 67,
                            Img = "/images/player_search/avatar_1.png",
                            Minutes = 34.7m,
                            Name = "Stephen Curry",
                            Points = 31.2m,
                            Rebounds = 5.5m,
                            Steals = 1.2m,
                            TeamId = 2,
                            TeamName = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 7,
                            Assists = 3.2m,
                            Ftps = 0.87m,
                            Games = 62,
                            Img = "/images/player_search/avatar_6.png",
                            Minutes = 31.0m,
                            Name = "Klay Thompson",
                            Points = 21.5m,
                            Rebounds = 3.9m,
                            Steals = 1.3m,
                            TeamId = 2,
                            TeamName = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 8,
                            Assists = 6.9m,
                            Ftps = 0.65m,
                            Games = 64,
                            Img = "/images/player_search/avatar_2.png",
                            Minutes = 28.3m,
                            Name = "Draymond Green",
                            Points = 8.5m,
                            Rebounds = 7.1m,
                            Steals = 1.5m,
                            TeamId = 2,
                            TeamName = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 9,
                            Assists = 3.4m,
                            Ftps = 0.76m,
                            Games = 66,
                            Img = "/images/player_search/avatar_3.png",
                            Minutes = 30.1m,
                            Name = "Andrew Wiggins",
                            Points = 17.3m,
                            Rebounds = 5.2m,
                            Steals = 1.0m,
                            TeamId = 2,
                            TeamName = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 10,
                            Assists = 8.8m,
                            Ftps = 0.83m,
                            Games = 58,
                            Img = "/images/player_search/avatar_5.png",
                            Minutes = 29.5m,
                            Name = "Chris Paul",
                            Points = 14.2m,
                            Rebounds = 4.1m,
                            Steals = 1.7m,
                            TeamId = 2,
                            TeamName = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 11,
                            Assists = 4.9m,
                            Ftps = 0.86m,
                            Games = 74,
                            Img = "/images/player_search/avatar_5.png",
                            Minutes = 36.5m,
                            Name = "Jayson Tatum",
                            Points = 30.1m,
                            Rebounds = 9.2m,
                            Steals = 1.4m,
                            TeamId = 3,
                            TeamName = "Boston Celtics"
                        },
                        new
                        {
                            Id = 12,
                            Assists = 3.5m,
                            Ftps = 0.80m,
                            Games = 70,
                            Img = "/images/player_search/avatar_3.png",
                            Minutes = 33.2m,
                            Name = "Jaylen Brown",
                            Points = 24.6m,
                            Rebounds = 6.3m,
                            Steals = 1.3m,
                            TeamId = 3,
                            TeamName = "Boston Celtics"
                        },
                        new
                        {
                            Id = 13,
                            Assists = 2.1m,
                            Ftps = 0.82m,
                            Games = 58,
                            Img = "/images/player_search/avatar_2.png",
                            Minutes = 28.7m,
                            Name = "Kristaps Porzingis",
                            Points = 20.4m,
                            Rebounds = 8.9m,
                            Steals = 1.2m,
                            TeamId = 3,
                            TeamName = "Boston Celtics"
                        },
                        new
                        {
                            Id = 14,
                            Assists = 4.0m,
                            Ftps = 0.85m,
                            Games = 65,
                            Img = "/images/player_search/avatar_1.png",
                            Minutes = 26.4m,
                            Name = "Derrick White",
                            Points = 11.2m,
                            Rebounds = 3.1m,
                            Steals = 1.0m,
                            TeamId = 3,
                            TeamName = "Boston Celtics"
                        },
                        new
                        {
                            Id = 15,
                            Assists = 2.8m,
                            Ftps = 0.79m,
                            Games = 60,
                            Img = "/images/player_search/avatar_6.png",
                            Minutes = 24.1m,
                            Name = "Al Horford",
                            Points = 9.5m,
                            Rebounds = 7.2m,
                            Steals = 0.8m,
                            TeamId = 3,
                            TeamName = "Boston Celtics"
                        },
                        new
                        {
                            Id = 16,
                            Assists = 5.4m,
                            Ftps = 0.90m,
                            Games = 70,
                            Img = "/images/player_search/avatar_6.png",
                            Minutes = 35.9m,
                            Name = "Kevin Durant",
                            Points = 29.8m,
                            Rebounds = 7.3m,
                            Steals = 1.1m,
                            TeamId = 4,
                            TeamName = "Brooklyn Nets"
                        },
                        new
                        {
                            Id = 17,
                            Assists = 6.5m,
                            Ftps = 0.55m,
                            Games = 55,
                            Img = "/images/player_search/avatar_1.png",
                            Minutes = 27.3m,
                            Name = "Ben Simmons",
                            Points = 6.8m,
                            Rebounds = 6.1m,
                            Steals = 1.4m,
                            TeamId = 4,
                            TeamName = "Brooklyn Nets"
                        },
                        new
                        {
                            Id = 18,
                            Assists = 3.2m,
                            Ftps = 0.83m,
                            Games = 68,
                            Img = "/images/player_search/avatar_2.png",
                            Minutes = 33.0m,
                            Name = "Mikal Bridges",
                            Points = 19.4m,
                            Rebounds = 4.8m,
                            Steals = 1.6m,
                            TeamId = 4,
                            TeamName = "Brooklyn Nets"
                        },
                        new
                        {
                            Id = 19,
                            Assists = 5.7m,
                            Ftps = 0.81m,
                            Games = 62,
                            Img = "/images/player_search/avatar_5.png",
                            Minutes = 28.4m,
                            Name = "Spencer Dinwiddie",
                            Points = 13.6m,
                            Rebounds = 2.9m,
                            Steals = 0.9m,
                            TeamId = 4,
                            TeamName = "Brooklyn Nets"
                        },
                        new
                        {
                            Id = 20,
                            Assists = 2.4m,
                            Ftps = 0.92m,
                            Games = 64,
                            Img = "/images/player_search/avatar_3.png",
                            Minutes = 23.9m,
                            Name = "Seth Curry",
                            Points = 11.5m,
                            Rebounds = 2.1m,
                            Steals = 0.7m,
                            TeamId = 4,
                            TeamName = "Brooklyn Nets"
                        },
                        new
                        {
                            Id = 21,
                            Assists = 5.4m,
                            Ftps = 0.84m,
                            Games = 69,
                            Img = "/images/player_search/avatar_3.png",
                            Minutes = 34.8m,
                            Name = "Jimmy Butler",
                            Points = 22.6m,
                            Rebounds = 5.8m,
                            Steals = 2.1m,
                            TeamId = 5,
                            TeamName = "Miami Heat"
                        },
                        new
                        {
                            Id = 22,
                            Assists = 3.5m,
                            Ftps = 0.77m,
                            Games = 71,
                            Img = "/images/player_search/avatar_2.png",
                            Minutes = 33.6m,
                            Name = "Bam Adebayo",
                            Points = 20.1m,
                            Rebounds = 9.4m,
                            Steals = 1.3m,
                            TeamId = 5,
                            TeamName = "Miami Heat"
                        },
                        new
                        {
                            Id = 23,
                            Assists = 4.3m,
                            Ftps = 0.86m,
                            Games = 66,
                            Img = "/images/player_search/avatar_6.png",
                            Minutes = 32.1m,
                            Name = "Tyler Herro",
                            Points = 21.2m,
                            Rebounds = 5.1m,
                            Steals = 1.0m,
                            TeamId = 5,
                            TeamName = "Miami Heat"
                        },
                        new
                        {
                            Id = 24,
                            Assists = 2.1m,
                            Ftps = 0.88m,
                            Games = 63,
                            Img = "/images/player_search/avatar_1.png",
                            Minutes = 24.5m,
                            Name = "Max Strus",
                            Points = 9.8m,
                            Rebounds = 3.2m,
                            Steals = 0.8m,
                            TeamId = 5,
                            TeamName = "Miami Heat"
                        },
                        new
                        {
                            Id = 25,
                            Assists = 2.3m,
                            Ftps = 0.85m,
                            Games = 58,
                            Img = "/images/player_search/avatar_5.png",
                            Minutes = 19.8m,
                            Name = "Gabe Vincent",
                            Points = 7.4m,
                            Rebounds = 2.0m,
                            Steals = 0.9m,
                            TeamId = 5,
                            TeamName = "Miami Heat"
                        },
                        new
                        {
                            Id = 26,
                            Assists = 8.7m,
                            Ftps = 0.83m,
                            Games = 74,
                            Img = "/images/player_search/avatar_5.png",
                            Minutes = 33.7m,
                            Name = "Nikola Jokic",
                            Points = 24.5m,
                            Rebounds = 10.8m,
                            Steals = 1.3m,
                            TeamId = 6,
                            TeamName = "Denver Nuggets"
                        },
                        new
                        {
                            Id = 27,
                            Assists = 6.1m,
                            Ftps = 0.89m,
                            Games = 68,
                            Img = "/images/player_search/avatar_1.png",
                            Minutes = 32.6m,
                            Name = "Jamal Murray",
                            Points = 20.3m,
                            Rebounds = 4.5m,
                            Steals = 1.4m,
                            TeamId = 6,
                            TeamName = "Denver Nuggets"
                        },
                        new
                        {
                            Id = 28,
                            Assists = 3.8m,
                            Ftps = 0.76m,
                            Games = 70,
                            Img = "/images/player_search/avatar_2.png",
                            Minutes = 31.5m,
                            Name = "Aaron Gordon",
                            Points = 17.2m,
                            Rebounds = 6.9m,
                            Steals = 1.1m,
                            TeamId = 6,
                            TeamName = "Denver Nuggets"
                        },
                        new
                        {
                            Id = 29,
                            Assists = 1.9m,
                            Ftps = 0.87m,
                            Games = 60,
                            Img = "/images/player_search/avatar_6.png",
                            Minutes = 27.4m,
                            Name = "Michael Porter Jr.",
                            Points = 14.1m,
                            Rebounds = 6.3m,
                            Steals = 0.9m,
                            TeamId = 6,
                            TeamName = "Denver Nuggets"
                        },
                        new
                        {
                            Id = 30,
                            Assists = 2.5m,
                            Ftps = 0.80m,
                            Games = 67,
                            Img = "/images/player_search/avatar_3.png",
                            Minutes = 25.8m,
                            Name = "Kentavious Caldwell-Pope",
                            Points = 10.2m,
                            Rebounds = 3.4m,
                            Steals = 1.2m,
                            TeamId = 6,
                            TeamName = "Denver Nuggets"
                        });
                });

            modelBuilder.Entity("Spovest.Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Img")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Не ожидал настолько хорошей игры, повешу счет игры в рамочке на стену !!!",
                            Img = "/images/user/stat.png",
                            Title = "Поднял бабло на баскетболе",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Опыт растёт с каждой игрой, теперь понимаю, где стоит рисковать, а где лучше подождать.",
                            Title = "Больше не боюсь делать ставки",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Но не расстроен, зато теперь знаю, как это работает на деле.",
                            Img = "/images/user/stat.png",
                            Title = "Поставил на проигравшую команду",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Content = "Раньше не особо разбирался в баскетболе, а сейчас даже прогнозы читаю перед матчами.",
                            Title = "Стало интереснее следить за спортом",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Это был шикарный момент! Теперь верю в свои силы и играю увереннее.",
                            Img = "/images/user/stat.png",
                            Title = "Выиграл первый крупный куш!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "Требует внимания и анализа, но когда всё сходится — адреналин зашкаливает!",
                            Title = "Сложная игра, но очень увлекательная",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "Всё было почти идеально, но в последние минуты всё пошло не так...",
                            Img = "/images/user/stat.png",
                            Title = "Обидное поражение",
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            Content = "Раньше действовал наугад, теперь проверяю форму игроков и результаты предыдущих встреч.",
                            Title = "Учу статистику перед ставками",
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            Content = "Изучил несколько подходов, адаптировал под себя — теперь стабильный плюс в кошельке.",
                            Img = "/images/user/stat.png",
                            Title = "Моя стратегия начала работать",
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            Content = "Главное — не гнаться за большими выигрышами, а держаться плана.",
                            Title = "Играю аккуратно, но уверенно",
                            UserId = 5
                        },
                        new
                        {
                            Id = 11,
                            Content = "Научился анализировать, стал больше понимать в спорте, чем раньше.",
                            Img = "/images/user/stat.png",
                            Title = "Крутой опыт за эти пару месяцев",
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            Content = "Теперь они тоже начали интересоваться, советуются по ставкам.",
                            Title = "Делюсь опытом с друзьями",
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            Content = "Уже несколько раз помогала выйти в плюс даже при небольших потерях.",
                            Img = "/images/user/stat.png",
                            Title = "Фора оказалась моим спасением",
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            Content = "Анализирую матчи, слежу за новостями, веду свою статистику — весело и полезно.",
                            Title = "Играть стало как хобби",
                            UserId = 7
                        },
                        new
                        {
                            Id = 15,
                            Content = "Проиграл, но без фанатизма, теперь буду учиться на этом опыте.",
                            Img = "/images/user/stat.png",
                            Title = "Первый минус, но не последний",
                            UserId = 8
                        },
                        new
                        {
                            Id = 16,
                            Content = "Пробую разные подходы, экспериментирую с суммами и выбором событий.",
                            Title = "Ищу свой стиль игры",
                            UserId = 8
                        },
                        new
                        {
                            Id = 17,
                            Content = "Раньше гнался за высокими цифрами, теперь выбираю более реальные варианты.",
                            Img = "/images/user/stat.png",
                            Title = "Стал осторожнее с коэффициентами",
                            UserId = 9
                        },
                        new
                        {
                            Id = 18,
                            Content = "Думаю развивать это дальше, может, станет проектом на постоянной основе.",
                            Title = "Создал телеграм-канал для обмена опытом",
                            UserId = 9
                        },
                        new
                        {
                            Id = 19,
                            Content = "Это добавляет адреналина, особенно если игра идет напряжённо до самого конца.",
                            Img = "/images/user/stat.png",
                            Title = "Люблю делать ставки в прямом эфире",
                            UserId = 10
                        },
                        new
                        {
                            Id = 20,
                            Content = "Теперь каждый момент важен, пытаюсь предсказать развитие событий.",
                            Title = "Смотрю матчи уже совсем по-другому",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("Spovest.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Purchase_price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Sale_price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayerId = 1,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            PlayerId = 2,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            PlayerId = 3,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            PlayerId = 4,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            PlayerId = 5,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            PlayerId = 6,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            PlayerId = 7,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            PlayerId = 8,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            PlayerId = 9,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            PlayerId = 10,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            PlayerId = 11,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            PlayerId = 12,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            PlayerId = 13,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            PlayerId = 14,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            PlayerId = 15,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            PlayerId = 16,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            PlayerId = 17,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            PlayerId = 18,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            PlayerId = 19,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            PlayerId = 20,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21,
                            PlayerId = 21,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            PlayerId = 22,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            PlayerId = 23,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            PlayerId = 24,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25,
                            PlayerId = 25,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26,
                            PlayerId = 26,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27,
                            PlayerId = 27,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28,
                            PlayerId = 28,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 29,
                            PlayerId = 29,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 30,
                            PlayerId = 30,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 31,
                            PlayerId = 1,
                            Purchase_price = 12m,
                            Sale_price = 10m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 32,
                            PlayerId = 2,
                            Purchase_price = 7m,
                            Sale_price = 8m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 33,
                            PlayerId = 3,
                            Purchase_price = 15m,
                            Sale_price = 14m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 34,
                            PlayerId = 4,
                            Purchase_price = 5m,
                            Sale_price = 6m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 35,
                            PlayerId = 5,
                            Purchase_price = 19m,
                            Sale_price = 17m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 36,
                            PlayerId = 6,
                            Purchase_price = 3m,
                            Sale_price = 4m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 37,
                            PlayerId = 7,
                            Purchase_price = 9m,
                            Sale_price = 9m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 38,
                            PlayerId = 8,
                            Purchase_price = 2m,
                            Sale_price = 3m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 39,
                            PlayerId = 9,
                            Purchase_price = 16m,
                            Sale_price = 15m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 40,
                            PlayerId = 10,
                            Purchase_price = 6m,
                            Sale_price = 7m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 41,
                            PlayerId = 11,
                            Purchase_price = 10m,
                            Sale_price = 10m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 42,
                            PlayerId = 12,
                            Purchase_price = 4m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 43,
                            PlayerId = 13,
                            Purchase_price = 18m,
                            Sale_price = 16m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 44,
                            PlayerId = 14,
                            Purchase_price = 8m,
                            Sale_price = 9m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 45,
                            PlayerId = 15,
                            Purchase_price = 1m,
                            Sale_price = 2m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 46,
                            PlayerId = 16,
                            Purchase_price = 14m,
                            Sale_price = 13m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 47,
                            PlayerId = 17,
                            Purchase_price = 11m,
                            Sale_price = 12m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 48,
                            PlayerId = 18,
                            Purchase_price = 5m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 49,
                            PlayerId = 19,
                            Purchase_price = 7m,
                            Sale_price = 8m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 50,
                            PlayerId = 20,
                            Purchase_price = 13m,
                            Sale_price = 12m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 51,
                            PlayerId = 21,
                            Purchase_price = 9m,
                            Sale_price = 10m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 52,
                            PlayerId = 22,
                            Purchase_price = 3m,
                            Sale_price = 4m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 53,
                            PlayerId = 23,
                            Purchase_price = 17m,
                            Sale_price = 15m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 54,
                            PlayerId = 24,
                            Purchase_price = 6m,
                            Sale_price = 7m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 55,
                            PlayerId = 25,
                            Purchase_price = 2m,
                            Sale_price = 3m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 56,
                            PlayerId = 26,
                            Purchase_price = 10m,
                            Sale_price = 9m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 57,
                            PlayerId = 27,
                            Purchase_price = 8m,
                            Sale_price = 8m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 58,
                            PlayerId = 28,
                            Purchase_price = 4m,
                            Sale_price = 5m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 59,
                            PlayerId = 29,
                            Purchase_price = 15m,
                            Sale_price = 14m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 60,
                            PlayerId = 30,
                            Purchase_price = 7m,
                            Sale_price = 6m,
                            Timestamp = new DateTime(2025, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Spovest.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FollowerId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("FollowerId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Spovest.Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Img")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img = "/images/teams/lakers.png",
                            Name = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 2,
                            Img = "/images/teams/gsw.png",
                            Name = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 3,
                            Img = "/images/teams/bc.png",
                            Name = "Boston Celtics"
                        },
                        new
                        {
                            Id = 4,
                            Img = "/images/teams/bn.png",
                            Name = "Brooklyn Nets"
                        },
                        new
                        {
                            Id = 5,
                            Img = "/images/teams/mh.png",
                            Name = "Miami Heat"
                        },
                        new
                        {
                            Id = 6,
                            Img = "/images/teams/dn.png",
                            Name = "Denver Nuggets"
                        });
                });

            modelBuilder.Entity("Spovest.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Spovest.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Spovest.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spovest.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Spovest.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Spovest.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Spovest.Domain.Entities.AppUser", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Follower");
                });
#pragma warning restore 612, 618
        }
    }
}
